version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=kimura
      - MONGO_PASS=root
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kimura
      - MONGO_INITDB_ROOT_PASSWORD=root
      
